import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";

const htmlPath = "frontend/index.html";
const cssPath = "frontend/css/styles.css";
const jsPath = "frontend/js/app.js";
const apiPath = "netlify/functions/rto-api.mjs";
const authPath = "netlify/functions/rto-auth.mjs";
const html = readFileSync(htmlPath, "utf8");
const css = readFileSync(cssPath, "utf8");
const js = readFileSync(jsPath, "utf8");
const api = readFileSync(apiPath, "utf8");
const auth = readFileSync(authPath, "utf8");
const toml = readFileSync("netlify.toml", "utf8");

assert(existsSync(htmlPath), "frontend HTML must exist");
assert(existsSync(cssPath), "extracted stylesheet must exist");
assert(existsSync(jsPath), "extracted browser JavaScript must exist");
assert.match(toml, /publish\s*=\s*"frontend"/, "Netlify must publish the frontend directory");
assert.match(html, /href=["']\/css\/styles\.css["']/, "HTML must reference the extracted stylesheet");
assert.match(html, /src=["']\/js\/app\.js["']/, "HTML must reference the extracted app script");
assert.doesNotMatch(html, /<style\b/i, "styles must not remain inline");
const scriptTags = [...html.matchAll(/<script\b([^>]*)>/gi)];
assert(scriptTags.every((match) => /\bsrc\s*=/.test(match[1])), "all scripts must be external files");
assert.match(css, /--pink\s*:\s*#FF2E88/i, "existing TapCore pink token must be preserved");
assert.match(css, /--cyan\s*:\s*#00E5FF/i, "existing signal cyan token must be preserved");
assert.match(js, /rtoApi/, "browser data access must use the server API");
assert.match(js, /QRCode/, "QR functionality must remain present");
assert.match(js, /renderPublicProfile/, "public business profile renderer must remain present");
assert.match(js, /renderOwnerGate/, "owner route must remain present");
assert.match(js, /renderAdminGate/, "admin route must remain present");
assert.doesNotMatch(js, /ADMIN_PASSCODE|RTO2026/, "admin passcode must not be hard-coded in browser JavaScript");
assert.match(js, /rtoApi\("admin-login"/, "admin authentication must be server-verified");
assert.match(js, /rtoApi\("owner-login"/, "owner access code must be server-verified");
assert.match(js, /rtoApi\("member-login"/, "member access code must be server-verified");
assert.match(api, /HttpOnly; Secure; SameSite=Lax/, "server sessions must use secure HttpOnly cookies");
assert.match(api, /SUPABASE_SERVICE_ROLE_KEY/, "privileged database access must remain server-side");
assert.doesNotMatch(js, /sb\.from\(/, "browser code must not query Supabase tables directly");
assert.doesNotMatch(js, /sb\.storage/, "browser code must not mutate Storage directly");
assert.match(api, /action === "customer-save"/, "business profile writes must pass through the API");
assert.match(api, /action === "review-submit"/, "review writes must pass through the API");
assert.match(api, /action === "booking-submit"/, "booking writes must pass through the API");
assert.match(api, /action === "booking-status"/, "booking status changes must be authorized server-side");
assert.match(api, /owner_code_hash/, "owner credentials must support hashed storage");
assert.match(api, /access_code_hash/, "member credentials must support hashed storage");
assert.match(api, /action === "upload-image"/, "image uploads must pass through validated server-side handling");
assert.match(api, /action === "delete-image"/, "image deletion must be authorized server-side");
assert.match(auth, /windowLimit: 15/, "authentication endpoint must have a stricter IP rate limit");
assert.match(js, /submitBooking/, "booking flow must remain present");
assert.match(js, /submitReview/, "review flow must remain present");
assert.match(js, /subscribeToLiveUpdates/, "Realtime subscription code must remain present");
assert.match(js, /IS_NETLIFY_PREVIEW/, "preview deployment must be detected");
assert.match(js, /Member sign-up is disabled in the verification preview/, "preview must block member writes");
assert.match(js, /Customer edits are disabled in the verification preview/, "preview must block customer edits");

console.log("RTO structural smoke checks passed. This does not certify authorization or end-to-end runtime behavior.");
