#!/usr/bin/env bash
set -euo pipefail

: "${DATABASE_URL:?DATABASE_URL must point to a disposable test PostgreSQL database}"

# This is intentionally a tiny test fixture, not a claim to reproduce the full
# production schema. It verifies that the two additive migrations execute,
# enforce their intended columns/defaults, and are safe to rerun.
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 <<'SQL'
CREATE TABLE public.customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
CREATE TABLE public.bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
SQL

psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100001_ensure_schedule_booking_fields.sql
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100002_add_customer_address_maps.sql

# Idempotency check: applying both forward migrations again must not fail.
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100001_ensure_schedule_booking_fields.sql
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100002_add_customer_address_maps.sql

psql "$DATABASE_URL" -v ON_ERROR_STOP=1 <<'SQL'
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'schedule'
      AND data_type = 'jsonb' AND is_nullable = 'NO'
  ) THEN RAISE EXCEPTION 'customers.schedule missing or has unexpected type/nullability'; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'booking_label'
      AND data_type = 'text' AND is_nullable = 'NO'
  ) THEN RAISE EXCEPTION 'customers.booking_label missing or has unexpected type/nullability'; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'item_requested'
      AND data_type = 'text'
  ) THEN RAISE EXCEPTION 'bookings.item_requested missing or has unexpected type'; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'address'
      AND data_type = 'text'
  ) THEN RAISE EXCEPTION 'customers.address missing or has unexpected type'; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'maps_url'
      AND data_type = 'text'
  ) THEN RAISE EXCEPTION 'customers.maps_url missing or has unexpected type'; END IF;

  IF (SELECT column_default FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'booking_label')
      NOT LIKE '%Book a visit%' THEN
    RAISE EXCEPTION 'customers.booking_label default is not the expected value';
  END IF;

  RAISE NOTICE 'RTO additive migration smoke tests passed';
END $$;
SQL

echo "RTO SQL migration smoke tests passed."
