#!/usr/bin/env bash
set -euo pipefail

: "${DATABASE_URL:?DATABASE_URL must point to a disposable test PostgreSQL database}"

# This is intentionally a small fixture, not a claim to reproduce the full
# production schema. It verifies additive schema changes and idempotent indexes.
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 <<'SQL'
CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE service_role NOLOGIN BYPASSRLS;
CREATE TABLE public.customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text UNIQUE,
  owner_code text
);
CREATE TABLE public.members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  access_code text NOT NULL
);
CREATE TABLE public.bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_slug text,
  member_id uuid
);
CREATE TABLE public.reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_slug text NOT NULL,
  member_id uuid NOT NULL
);
CREATE TABLE public.page_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL
);
SQL

psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100001_ensure_schedule_booking_fields.sql
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100002_add_customer_address_maps.sql
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100003_add_review_uniqueness_and_query_indexes.sql
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100004_hash_access_codes.sql
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100005_lock_direct_client_data_access.sql
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100006_rto_storage_limits.sql

# Idempotency check: applying all six forward migrations again must not fail.
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100001_ensure_schedule_booking_fields.sql
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100002_add_customer_address_maps.sql
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100003_add_review_uniqueness_and_query_indexes.sql
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100004_hash_access_codes.sql
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100005_lock_direct_client_data_access.sql
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/202610100006_rto_storage_limits.sql

psql "$DATABASE_URL" -v ON_ERROR_STOP=1 <<'SQL'
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'schedule'
      AND data_type = 'jsonb' AND is_nullable = 'NO'
  ) THEN RAISE EXCEPTION 'customers.schedule missing or has unexpected type/nullability'; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'booking_label'
      AND data_type = 'text' AND is_nullable = 'NO'
  ) THEN RAISE EXCEPTION 'customers.booking_label missing or has unexpected type/nullability'; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'bookings' AND column_name = 'item_requested'
      AND data_type = 'text'
  ) THEN RAISE EXCEPTION 'bookings.item_requested missing or has unexpected type'; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'address'
      AND data_type = 'text'
  ) THEN RAISE EXCEPTION 'customers.address missing or has unexpected type'; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'maps_url'
      AND data_type = 'text'
  ) THEN RAISE EXCEPTION 'customers.maps_url missing or has unexpected type'; END IF;

  IF (SELECT column_default FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'booking_label')
      NOT LIKE '%Book a visit%' THEN
    RAISE EXCEPTION 'customers.booking_label default is not the expected value';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'customers' AND column_name = 'owner_code_hash' AND data_type = 'text') THEN
    RAISE EXCEPTION 'customers.owner_code_hash missing';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'members' AND column_name = 'access_code_hash' AND data_type = 'text') THEN
    RAISE EXCEPTION 'members.access_code_hash missing';
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'members' AND column_name = 'access_code' AND is_nullable = 'NO') THEN
    RAISE EXCEPTION 'members.access_code must allow null after hashed migration';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'reviews_business_slug_member_id_uidx' AND indexdef LIKE 'CREATE UNIQUE INDEX%') THEN
    RAISE EXCEPTION 'Review upsert unique index missing';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'bookings_business_slug_idx') THEN
    RAISE EXCEPTION 'bookings.business_slug index missing';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'bookings_member_id_idx') THEN
    RAISE EXCEPTION 'bookings.member_id index missing';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'page_events_slug_idx') THEN
    RAISE EXCEPTION 'page_events.slug index missing';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'reviews_member_id_idx') THEN
    RAISE EXCEPTION 'reviews.member_id index missing';
  END IF;

  IF EXISTS (
    SELECT 1 FROM pg_tables
    WHERE schemaname = 'public'
      AND tablename IN ('customers','members','reviews','bookings','page_events')
      AND NOT rowsecurity
  ) THEN
    RAISE EXCEPTION 'RTO tables must have RLS enabled';
  END IF;
  IF has_table_privilege('anon', 'public.customers', 'SELECT')
     OR has_table_privilege('anon', 'public.customers', 'INSERT')
     OR has_table_privilege('authenticated', 'public.bookings', 'UPDATE') THEN
    RAISE EXCEPTION 'Direct client privileges remain on protected RTO tables';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename IN ('customers','members','reviews','bookings','page_events')) THEN
    RAISE EXCEPTION 'Direct client policies remain on protected RTO tables';
  END IF;

  RAISE NOTICE 'RTO migration smoke tests passed';
END $$;
SQL

echo "RTO SQL migration smoke tests passed."
