-- Idempotent RTO schema baseline for fresh installs and drift documentation.
-- Existing tables are intentionally not dropped or rewritten. Forward migrations
-- below this timestamp add fields/indexes and enforce the target access model.
-- This file does not configure the Storage bucket; migration 006 does that.

CREATE TABLE IF NOT EXISTS public.customers (
  slug text PRIMARY KEY,
  name text NOT NULL,
  title text,
  phone text,
  whatsapp_number text,
  whatsapp_message text,
  google_review_url text,
  instagram text,
  linkedin text,
  till_number text,
  till_label text,
  portfolio jsonb DEFAULT '[]'::jsonb,
  photo_url text,
  background_url text,
  created_at timestamptz DEFAULT now(),
  menu_items jsonb DEFAULT '[]'::jsonb,
  menu_image_url text,
  portfolio_title text DEFAULT 'Recent work',
  business_type text,
  theme text DEFAULT 'neon',
  social_links jsonb DEFAULT '[]'::jsonb,
  owner_code text,
  is_open boolean DEFAULT true,
  connect_label text DEFAULT 'Connect',
  pay_label text DEFAULT 'Pay',
  menu_label text DEFAULT 'Menu',
  cover_style text DEFAULT 'compact',
  cover_overlay integer DEFAULT 40,
  listed_in_directory boolean DEFAULT true,
  booking_guidelines text,
  status_on_label text DEFAULT 'Open',
  status_off_label text DEFAULT 'Closed'
);

CREATE TABLE IF NOT EXISTS public.members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  phone text NOT NULL,
  access_code text NOT NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT members_phone_key UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS public.reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_slug text,
  member_id uuid,
  member_name text,
  rating integer NOT NULL,
  comment text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT reviews_rating_check CHECK (rating >= 1 AND rating <= 5),
  CONSTRAINT reviews_business_slug_fkey FOREIGN KEY (business_slug) REFERENCES public.customers(slug) ON DELETE CASCADE,
  CONSTRAINT reviews_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE,
  CONSTRAINT reviews_business_slug_member_id_key UNIQUE (business_slug, member_id)
);

CREATE TABLE IF NOT EXISTS public.bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_slug text,
  member_id uuid,
  customer_name text,
  customer_phone text,
  preferred_date text,
  preferred_time text,
  note text,
  status text DEFAULT 'pending',
  created_at timestamptz DEFAULT now(),
  CONSTRAINT bookings_business_slug_fkey FOREIGN KEY (business_slug) REFERENCES public.customers(slug) ON DELETE CASCADE,
  CONSTRAINT bookings_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.page_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text,
  event_type text NOT NULL,
  link_label text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT page_events_slug_fkey FOREIGN KEY (slug) REFERENCES public.customers(slug) ON DELETE CASCADE
);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.page_events ENABLE ROW LEVEL SECURITY;

-- The server-only API uses the service_role key and must retain access after
-- the client roles are locked down in migration 005.
GRANT ALL PRIVILEGES ON TABLE public.customers, public.members, public.reviews, public.bookings, public.page_events TO service_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;
